/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author asus
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Pharmacy() {
        initComponents();
        setLocationRelativeTo(null);
        update.setVisible(false);
        insert.setVisible(false);
        delete.setVisible(false);
        
    }
       
    String URL = "jdbc:mysql://localhost:3306/hospital_management";
    String User = "root";
    String Password = "root9408";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        option = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        idlabel = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        company = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        expiry = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mrp = new javax.swing.JTextField();
        cp = new javax.swing.JTextField();
        sp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mfg = new com.toedter.calendar.JDateChooser();
        date = new com.toedter.calendar.JDateChooser();
        avail = new javax.swing.JTextField();
        fetch = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pharmacy = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CITY HOSPITAL");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medicine-cart-icon-64p.png"))); // NOI18N
        jLabel2.setText("Store");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Select from the option");

        option.setBackground(new java.awt.Color(153, 255, 204));
        option.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Insert", "Update", "Delete" }));
        option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionActionPerformed(evt);
            }
        });
        option.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                optionKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        idlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idlabel.setText("MID");

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFocusGained(evt);
            }
        });
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMouseClicked(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Medicine Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Availability");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Expiry Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Manufacturing Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Company");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Date of Purchase");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setPreferredSize(new java.awt.Dimension(7, 23));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
        });
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameMouseClicked(evt);
            }
        });

        company.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        company.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                companyFocusGained(evt);
            }
        });
        company.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyMouseClicked(evt);
            }
        });

        insert.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        expiry.setDateFormatString("yyyy-MM-dd");
        expiry.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        expiry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                expiryFocusLost(evt);
            }
        });
        expiry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expiryMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                expiryMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                expiryMouseReleased(evt);
            }
        });
        expiry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expiryKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("MRP.");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Selling Price");

        mrp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mrp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mrpFocusGained(evt);
            }
        });
        mrp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mrpMouseClicked(evt);
            }
        });

        cp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpFocusGained(evt);
            }
        });
        cp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpMouseClicked(evt);
            }
        });

        sp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spFocusGained(evt);
            }
        });
        sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Cost Price");

        mfg.setDateFormatString("yyyy-MM-dd");
        mfg.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        mfg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mfgFocusLost(evt);
            }
        });
        mfg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mfgMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mfgMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mfgMouseReleased(evt);
            }
        });
        mfg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mfgKeyReleased(evt);
            }
        });

        date.setDateFormatString("yyyy-MM-dd");
        date.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFocusLost(evt);
            }
        });
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dateMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dateMouseReleased(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateKeyReleased(evt);
            }
        });

        avail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        avail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                availFocusGained(evt);
            }
        });
        avail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availMouseClicked(evt);
            }
        });
        avail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                availKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                availKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mrp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expiry, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mfg, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avail, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(avail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mfg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mrp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        fetch.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        fetch.setText("Fetch Data");
        fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "by Name", "by ID and Name" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Downloads\\Compressed\\HMS ICON\\back.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        table_pharmacy.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        table_pharmacy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MID", "Medicine Name", "Availability", "Mfg. Date", "Expiry Date", "Date", "Company", "MRP", "Cost Price", "Selling Price"
            }
        ));
        table_pharmacy.setEnabled(false);
        table_pharmacy.setRowHeight(30);
        jScrollPane1.setViewportView(table_pharmacy);
        if (table_pharmacy.getColumnModel().getColumnCount() > 0) {
            table_pharmacy.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79)
                        .addComponent(option, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fetch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logout))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(option, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fetch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionActionPerformed
        switch (option.getSelectedIndex()) {
            case 0:
            update.setVisible(false);
            insert.setVisible(false);
            delete.setVisible(false);
            idlabel.setVisible(true);
            id.setVisible(true);
            jLabel5.setVisible(true);jLabel6.setVisible(true);jLabel7.setVisible(true);jLabel8.setVisible(true);
            jLabel9.setVisible(true);jLabel10.setVisible(true);jLabel11.setVisible(true);jLabel12.setVisible(true);
            avail.setVisible(true);mrp.setVisible(true);cp.setVisible(true);sp.setVisible(true);company.setVisible(true);mfg.setVisible(true);expiry.setVisible(true);date.setVisible(true);
            break;
            case 1:
            update.setVisible(false);
            insert.setVisible(true);
            delete.setVisible(false);
            idlabel.setVisible(false);
            id.setVisible(false);
            jLabel5.setVisible(true);jLabel6.setVisible(true);jLabel7.setVisible(true);jLabel8.setVisible(true);
            jLabel9.setVisible(true);jLabel10.setVisible(true);jLabel11.setVisible(true);jLabel12.setVisible(true);
            avail.setVisible(true);mrp.setVisible(true);cp.setVisible(true);sp.setVisible(true);company.setVisible(true);mfg.setVisible(true);expiry.setVisible(true);date.setVisible(true);
            break;
            case 2:
            update.setVisible(true);
            insert.setVisible(false);
            delete.setVisible(false);
            idlabel.setVisible(true);
            id.setVisible(true);
            jLabel5.setVisible(true);jLabel6.setVisible(true);jLabel7.setVisible(true);jLabel8.setVisible(true);
            jLabel9.setVisible(true);jLabel10.setVisible(true);jLabel11.setVisible(true);jLabel12.setVisible(true);
            avail.setVisible(true);mrp.setVisible(true);cp.setVisible(true);sp.setVisible(true);company.setVisible(true);mfg.setVisible(true);expiry.setVisible(true);date.setVisible(true);
            break;
            case 3:
            update.setVisible(false);
            insert.setVisible(false);
            delete.setVisible(true);
            idlabel.setVisible(true);
            id.setVisible(true);
            jLabel5.setVisible(false);jLabel6.setVisible(false);jLabel7.setVisible(false);jLabel8.setVisible(false);
            jLabel9.setVisible(false);jLabel10.setVisible(false);jLabel11.setVisible(false);jLabel12.setVisible(false);
            avail.setVisible(false);mrp.setVisible(false);cp.setVisible(false);sp.setVisible(false);company.setVisible(false);mfg.setVisible(false);expiry.setVisible(false);date.setVisible(false);
            break;
            default:
            update.setVisible(false);
            insert.setVisible(false);
            delete.setVisible(false);
            jLabel5.setVisible(true);jLabel6.setVisible(true);jLabel7.setVisible(true);jLabel8.setVisible(true);
            jLabel9.setVisible(true);jLabel10.setVisible(true);jLabel11.setVisible(true);jLabel12.setVisible(true);
            avail.setVisible(true);mrp.setVisible(true);cp.setVisible(true);sp.setVisible(true);company.setVisible(true);mfg.setVisible(true);expiry.setVisible(true);date.setVisible(true);
            break;
        }
    }//GEN-LAST:event_optionActionPerformed

    private void optionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_optionKeyTyped

    private void idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusGained
        id.setText("");
    }//GEN-LAST:event_idFocusGained

    private void idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseClicked
        id.setText("");
    }//GEN-LAST:event_idMouseClicked

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        if (option.getSelectedIndex()==2) {
            int m_id = Integer.parseInt(id.getText());
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(URL, User, Password);
                PreparedStatement pst = con.prepareStatement("Select * from Medicines where MID = ?");
                pst.setInt(1, m_id);

                ResultSet rs = pst.executeQuery();
                if(rs.next()){
             
                String mavail = rs.getString(2);
                String mmfg = rs.getString(3);
                String mexpiry = rs.getString(4);
                String mpurchase = rs.getString(5);
                String mcompany = rs.getString(6);
                String mmrp = rs.getString(7);
                String mcp = rs.getString(8);
                String msp = rs.getString(9);
                String mname = rs.getString(10);

                    name.setText(mname);company.setText(mcompany);avail.setText(mavail);mrp.setText(mmrp);cp.setText(mcp);sp.setText(msp);
                    ((JTextField)expiry.getDateEditor().getUiComponent()).setText(mexpiry);((JTextField)mfg.getDateEditor().getUiComponent()).setText(mmfg);
                    ((JTextField)date.getDateEditor().getUiComponent()).setText(mpurchase);

                }
                else{
                    name.setText("");company.setText("");avail.setText("");mrp.setText("");cp.setText("");sp.setText("");
                    ((JTextField)expiry.getDateEditor().getUiComponent()).setText("");((JTextField)mfg.getDateEditor().getUiComponent()).setText("");
                    ((JTextField)date.getDateEditor().getUiComponent()).setText("");
                }

            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_idKeyReleased

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped

    }//GEN-LAST:event_idKeyTyped

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        name.setText("");
    }//GEN-LAST:event_nameFocusGained

    private void nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseClicked
        name.setText("");
    }//GEN-LAST:event_nameMouseClicked

    private void companyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_companyFocusGained
        company.setText("");
    }//GEN-LAST:event_companyFocusGained

    private void companyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyMouseClicked
        company.setText("");
    }//GEN-LAST:event_companyMouseClicked

    @SuppressWarnings("ConvertToTryWithResources")
    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(URL, User, Password);
            String query = "Insert into Medicines( Name, Availability, MFG, Expiry, DateOfPurchase, Company, MRP, CP, SP) values(?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, name.getText());
            pst.setString(2, avail.getText());
            pst.setString(3, ((JTextField)mfg.getDateEditor().getUiComponent()).getText());
            pst.setString(4, ((JTextField)expiry.getDateEditor().getUiComponent()).getText());
            pst.setString(5, ((JTextField)date.getDateEditor().getUiComponent()).getText());
            pst.setString(6, company.getText());
            pst.setDouble(7, Double.parseDouble(mrp.getText()));
            pst.setDouble(8, Double.parseDouble(cp.getText()));
            pst.setDouble(9, Double.parseDouble(sp.getText()));

            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Data Inserted !");
            pst.close();
            con.close();
        }
        catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int m_id = Integer.parseInt(id.getText());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(URL, User, Password);
            PreparedStatement pst = con.prepareStatement("Update Medicines set Name=?, Availability=?, MFG=?, Expiry=?, DateOfPurchase=?, Company=?, MRP=?, CP=?, SP=? where MID=?");

            pst.setString(1, name.getText());
            pst.setString(2, avail.getText());
            pst.setString(3, ((JTextField)expiry.getDateEditor().getUiComponent()).getText());
            pst.setString(4, ((JTextField)expiry.getDateEditor().getUiComponent()).getText());
            pst.setString(5, ((JTextField)expiry.getDateEditor().getUiComponent()).getText());
            pst.setString(6, company.getText());
            pst.setDouble(7, Double.parseDouble(mrp.getText()));
            pst.setDouble(8, Double.parseDouble(cp.getText()));
            pst.setDouble(9, Double.parseDouble(sp.getText()));
            pst.setInt(10, m_id);
            
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Updated Successfully !");

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int m_id = new Integer(id.getText());
        String m_name = name.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(URL, User, Password);
            PreparedStatement pst = con.prepareStatement("Delete from Medicines where MID = ? and Name = ? ");
            pst.setInt(1, m_id);
            pst.setString(2, m_name);

            pst.execute();

            JOptionPane.showMessageDialog(null, "Deleted Successfuly ! ");
        }
        catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void expiryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expiryFocusLost

    }//GEN-LAST:event_expiryFocusLost

    private void expiryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiryMouseClicked

    }//GEN-LAST:event_expiryMouseClicked

    private void expiryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiryMouseExited

    }//GEN-LAST:event_expiryMouseExited

    private void expiryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expiryMouseReleased

    }//GEN-LAST:event_expiryMouseReleased

    private void expiryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiryKeyReleased

    }//GEN-LAST:event_expiryKeyReleased

    private void fetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchActionPerformed
        table_pharmacy.setModel(new DefaultTableModel(null, new String[]{"MID", "Medicine Name", "Availability", " MFG", "Expiry", "Date of Purchase", "Company", "MRP", "Cost Price", "Selling Price"}));
        table_pharmacy.getColumnModel().getColumn(1).setPreferredWidth(200);
        DefaultTableModel model = (DefaultTableModel)table_pharmacy.getModel();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(URL, User, Password);
            Statement stmt = con.createStatement();
            String query = "Select * from medicines";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                int mid = rs.getInt(1);               
                String mavail = rs.getString(2);
                String mmfg = rs.getString(3);
                String mexpiry = rs.getString(4);
                String mpurchase = rs.getString(5);
                String mcompany = rs.getString(6);
                String mmrp = rs.getString(7);
                String mcp = rs.getString(8);
                String msp = rs.getString(9);
                String mname = rs.getString(10);
                

                model.addRow(new Object[]{mid, mname, mavail, mmfg, mexpiry, mpurchase, mcompany, mmrp, mcp, msp});

            }

        }
        catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_fetchActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        table_pharmacy.setModel(new DefaultTableModel(null, new String[]{"MID", "Medicine Name", "Availability", " MFG", "Expiry", "Date of Purchase", "Company", "MRP", "Cost Price", "Selling Price"}));
        table_pharmacy.getColumnModel().getColumn(1).setPreferredWidth(200);
        DefaultTableModel model = (DefaultTableModel)table_pharmacy.getModel();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(URL, User, Password);
            PreparedStatement pst=null;

            if (jComboBox1.getSelectedIndex()==0) {
                String query = "Select * from Medicines where Name =?";
                pst = con.prepareStatement(query);
                pst.setString(1, name.getText());
            }
            if(jComboBox1.getSelectedIndex()==1){
                String query = "Select * from Medicines where mid=? and Name =?";
                pst = con.prepareStatement(query);
                pst.setInt(1, new Integer(id.getText()));
                pst.setString(2, name.getText());
            }

            @SuppressWarnings("null")
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                int mid = rs.getInt(1);               
                String mavail = rs.getString(2);
                String mmfg = rs.getString(3);
                String mexpiry = rs.getString(4);
                String mpurchase = rs.getString(5);
                String mcompany = rs.getString(6);
                String mmrp = rs.getString(7);
                String mcp = rs.getString(8);
                String msp = rs.getString(9);
                String mname = rs.getString(10);

                model.addRow(new Object[]{mid, mname, mavail, mmfg, mexpiry, mpurchase, mcompany, mmrp, mcp, msp});
            }

        }
        catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int x = JOptionPane.showConfirmDialog(this, "Do you really want to logout ?","Confirm" ,JOptionPane.YES_NO_OPTION);
        if (x==0) {
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void mrpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mrpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_mrpFocusGained

    private void mrpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mrpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mrpMouseClicked

    private void cpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cpFocusGained

    private void cpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cpMouseClicked

    private void spFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spFocusGained

    private void spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spMouseClicked

    private void mfgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mfgFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgFocusLost

    private void mfgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mfgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgMouseClicked

    private void mfgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mfgMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgMouseExited

    private void mfgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mfgMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgMouseReleased

    private void mfgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mfgKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mfgKeyReleased

    private void dateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFocusLost

    private void dateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dateMouseClicked

    private void dateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dateMouseExited

    private void dateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateMouseReleased

    private void dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateKeyReleased

    private void availFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_availFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_availFocusGained

    private void availMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_availMouseClicked

    private void availKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_availKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_availKeyReleased

    private void availKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_availKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_availKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Pharmacy().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avail;
    private javax.swing.JButton back;
    private javax.swing.JTextField company;
    private javax.swing.JTextField cp;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton delete;
    private com.toedter.calendar.JDateChooser expiry;
    private javax.swing.JButton fetch;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idlabel;
    private javax.swing.JButton insert;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private com.toedter.calendar.JDateChooser mfg;
    private javax.swing.JTextField mrp;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> option;
    private javax.swing.JButton search;
    private javax.swing.JTextField sp;
    private javax.swing.JTable table_pharmacy;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
